spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
    password: postgres
    hikari:
      schema: test_schema
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration