server:
  servlet:
    context-path: "/"
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
    password: postgres
    hikari:
      schema: test_schema
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
limits:
  standard: 10000
scheduler:
  limits_reset_cron: 0 0 0 * * *